spring:
  application:
    name: cgmes-utility-service
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 500MB
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  tracing:
    sampling:
      probability: 1.0
otel:
  service:
    name: cgmes-utility-service
  traces:
    exporter: otlp
  metrics:
    exporter: otlp
  logs:
    exporter: none
logging:
  level:
    eu.tscnet: INFO
    org.apache.jena: WARN
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
